
spring.datasource.url=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml

spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}

jwt.secret=${JWT_SECRET}
jwt.access.expirationMs=${JWT_ACCESS_EXPIRATION_MS}
jwt.refresh.expirationMs=${JWT_REFRESH_EXPIRATION_MS}
jwt.blacklist.prefix=auth:blacklist:
jwt.refresh.prefix=auth:storage:

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.security=DEBUG

server.port=${AUTHENTICATION_PORT}