spring.application.name=authentication-service

# Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/innowise_authentication_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Liquibase Configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml

# Logging Configuration
logging.level.org.springframework.security=DEBUG

# Temporary properties
spring.docker.compose.enabled=false
logging.level.liquibase=DEBUG
logging.level.org.springframework.jdbc.core=TRACE

# JWT Settings
jwt.secret=nQ9XKp3Lv6yRf8jWtEwP2bGc7ZmY5xH1v4Sd0AaBbCcDdEeFfGgHhIiJjJkKlLmMnNoPqQrRsStTuU
jwt.access.expirationMs=600000
jwt.refresh.expirationMs=86400000
jwt.blacklist.prefix=auth:blacklist:
jwt.refresh.prefix=auth:storage:

# Redis properties
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.database=0
spring.data.redis.timeout=2000ms
spring.data.redis.jedis.pool.max-active=8
spring.data.redis.jedis.pool.max-idle=8
spring.data.redis.jedis.pool.min-idle=0

server.port=8081